#!/bin/bash

R="$(printf '\033[1;31m')"
G="$(printf '\033[1;32m')"
Y="$(printf '\033[1;33m')"
W="$(printf '\033[1;37m')"
C="$(printf '\033[1;36m')"

function banner() {
    clear
	
printf "\033[33m╭━━━╮╱╱╱╱╱╱╱╱╱╱╱╱╭━━╮╱╱╱╭━━━━╮\033[0m\n"
printf "\033[33m┃╭━╮┃╱╱╱╱╱╱╱╱╱╱╱╱╰┫┣╯╱╱╱┃╭╮╭╮┃\033[0m\n"
printf "\033[33m┃┃╱╰╋━╮╭━━┳╮╭┳━━╮╱┃┃╭━╮╱╰╯┃┃┣┻━┳━┳╮╭┳╮╭┳╮╭╮\033[0m\n"
printf "\033[33m┃┃╭━┫╭╮┫╭╮┃╰╯┃┃━┫╱┃┃┃╭╮╮╱╱┃┃┃┃━┫╭┫╰╯┃┃┃┣╋╋╯\033[0m\n"
printf "\033[33m┃╰┻━┃┃┃┃╰╯┃┃┃┃┃━┫╭┫┣┫┃┃┃╱╱┃┃┃┃━┫┃┃┃┃┃╰╯┣╋╋╮\033[0m\n"
printf "\033[33m╰━━━┻╯╰┻━━┻┻┻┻━━╯╰━━┻╯╰╯╱╱╰╯╰━━┻╯╰┻┻┻━━┻╯╰╯\033[0m\n"
echo "${C}${BOLD} Install Gnome Desktop In Termux ${W}"
echo                                                    
}

function package_install_and_check() {
	packs_list=($@)
	for package_name in "${packs_list[@]}"; do
    echo "${R}[${W}-${R}]${G}${BOLD} Installing package: ${C}$package_name "${W}
    apt install "$package_name" -y
	if [ $? -ne 0 ]; then
    apt --fix-broken install -y
	dpkg --Configuring -a
    fi
	if dpkg -s "$package_name" >/dev/null 2>&1; then
    echo "${R}[${W}-${R}]${G} $package_name installed successfully "${W}
	else
	if
    type -p "$package_name" &>/dev/null || [ -e "$PREFIX/bin/$package_name"* ] || [ -e "$PREFIX/bin/"*"$package_name" ]; then
        echo "${R}[${W}-${R}]${C} $package_name ${G}installed successfully "${W}
	fi
    fi
done

}

function check_root(){
	if [ $EUID -ne 0 ]; then
		echo -ne " ${R}Please Login Into Root User Then Run it Again!\n\n"${W}
		exit 1
	fi
}

function questions() {
	banner
	echo 
	echo "${R} [${W}-${R}]${G}Select browser you want to install"${W}
	echo
	echo "${Y}1. firefox"${W}
	echo
	echo "${Y}2. chromium"${W}
	echo 
	echo "${Y}3. firefox & chromium (both)"${W}
	echo
	read -p "${Y}select an option (Default 1): "${W} answer_browser
    answer_browser=${answer_browser:-1} 
	echo
	echo "${R}[${W}-${R}]${G}Continuing with answer: $answer_browser"${W}
	sleep 0.2
	banner
	read -p "${R} [${W}-${R}]${Y}Do you want to install VLC (y/n) "${W} vlc_answer
    vlc_answer=${vlc_answer:-y} 
	echo
	echo "${R}[${W}-${R}]${G}Continuing with answer: $vlc_answer"${W}
	sleep 0.2
    banner
    read -p "${R} [${W}-${R}]${Y}Do you want to create a normal user account (y/n) "${W} useradd_answer
    useradd_answer="${useradd_answer:-y}"
    echo "${R}[${W}-${R}]${G}Continuing with answer: $useradd_answer"${W}
    sleep 0.2
    banner
    if [[ "$useradd_answer" == "n" ]]; then
    banner
    echo "${R} [${W}-${R}]${G}Skiping User Account Setup"${W}
    else
    echo "${R} [${W}-${R}]${G}Create user account"${W}
    echo
    while true; do
    read -p "${R} [${W}-${R}]${G}Input username [Lowercase]: "${W} user_name
    echo
    read -p "${R} [${W}-${R}]${G}Input Password: "${W} pass
    echo
    read -p "${R} [${W}-${R}]${Y}Do you want to continue with username ${C}$user_name ${Y}and password ${C}$pass${Y} ? (y/n) : " choice
	choice="${choice:-y}"
    case $choice in
        [yY]* )
            echo "${R} [${W}-${R}]${G}Continuing with username ${C}$user_name ${G}and password ${C}$pass"
            sleep 0.3
            break;;
        [nN]* )
            echo "${G}Skipping useradd step"${W}
            sleep 0.3
            break;;
        * )
            echo "${R}Invalid input. Please enter 'y' or 'n'."${W}
            ;;
    esac
done
    fi
}

function get_sys_info() {
	if [ -f /etc/os-release ]; then
    . /etc/os-release
	if [[ -e "/data/data/com.termux/files/usr/bin/$ID" ]]; then
        rm -rf /data/data/com.termux/files/usr/bin/$ID
    fi
	fi
}

function update_sys() {
	banner
	echo "${R} [${W}-${R}]${G}Updating ${ID}'s System..."
	apt update && apt-get update 
}

function setup_tx11() {
    if [ "$useradd_answer" == "y" ]; then
    final_user="$user_name"
    else
    final_user="root"
    fi
cat <<EOF >> "/data/data/com.termux/files/usr/bin/$ID"

session_dir="\$HOME/.cache/sessions"
if [ -d "\$session_dir" ]; then
    files_to_remove=\$(find "\$session_dir" -type f -name 'x*')
    if [ -n "\$files_to_remove" ]; then
        rm "\$session_dir"/x* > /dev/null 2>&1
    fi
fi
if [ "\$1" = "-remove" ]; then
    proot-distro remove $ID
	rm /data/data/com.termux/files/home/.${ID}-sound-service
	rm \$PREFIX/bin/$ID
elif [ "\$1" = "-r" ]; then
    proot-distro login $ID
elif [ "\$1" = "-tx11" ]; then
    pkill -f com.termux.x11 2>/dev/null
termux-x11 :0 >/dev/null &
sleep 3
am start --user 0 -n com.termux.x11/com.termux.x11.MainActivity > /dev/null 2>&1
sleep 1
proot-distro login $ID --user $final_user --shared-tmp -- /bin/bash -c "sudo service dbus start && export XDG_CURRENT_DESKTOP="GNOME" && env DISPLAY=:0 gnome-shell --x11"
exit 0
else
    proot-distro login --user $final_user $ID
fi
EOF
chmod +x /data/data/com.termux/files/usr/bin/$ID
echo -e "${R} [${W}-${R}]${C} Fixing Login Issue.."${W}
   for file in $(find /usr -type f -iname "*login1*"); do rm -rf $file
   done
}


function login() {
	banner
	if [ "$useradd_answer" == "y" ]; then
    groupadd storage
    groupadd wheel
	useradd -m -g users -s $(which bash) ${user_name}
    usermod -aG wheel,polkitd,audio,video,storage ${user_name}
    echo "${user_name}:${pass}" | chpasswd
	apt install sudo -y
    echo "$user_name ALL=(ALL:ALL) ALL" | tee -a /etc/sudoers
fi   
}

function vlc_installer() {
	banner
if [ "$vlc_answer" == "y" ]; then
	echo "${R} [${W}-${R}]${G}Installing vlc.."${W}
		package_install_and_check "vlc"
else
    echo "${R} [${W}-${R}]${C}Canceling Vlc Installation...."${W}
    sleep 1.5
fi
}

function install_chromium() {
	banner
	echo "${R} [${W}-${R}]${G} installing chromium..."${W}
    package_install_and_check "chromium"
    sed -i 's/chromium %U/chromium --no-sandbox %U/g' /usr/share/applications/chromium.desktop
}

function firefox_install() {
		clear
		banner
		sleep 1
		clear
        echo "${R} [${W}-${R}]${Y} Installing Firefox..."${W}
		echo
        package_install_and_check "firefox-esr"
}

function browser_installer() {
	banner
	if [[ ${answer_browser} == "1" ]]; then 
		firefox_install
	elif [[ ${answer_browser} == "2" ]]; then
		install_chromium
	elif [[ ${answer_browser} == "3" ]]; then
		firefox_install
		install_chromium
	elif [[ ${answer_browser} == "" ]]; then 
		firefox_install
	else 
		firefox_install
	fi
}

function install_gnome_core() {
	echo "${R} [${W}-${R}]${G}Installing Gnome Core.."${W}
	sleep 2
    update_sys
    package_install_and_check "pardus-gnome-desktop gnome-terminal gnome-tweaks gnome-tweaks gnome-software nautilus gnome-shell-extension-manager"
	clear
}
	
function package() {
	banner
    echo -e "${R} [${W}-${R}]${C} Checking required packages..."${W}
    apt update
    package_install_and_check "sudo nano wget software-properties-common gnupg2 dbus-x11"
}

function install_desktop() {
    banner
    install_gnome_core
}

function add_sound() {
	echo -e "\n${R} [${W}-${R}]${C} Fixing Sound Problem..."${W}
    if [[ ! -e "/data/data/com.termux/files/home/.${ID}-sound-service" ]]; then
        touch /data/data/com.termux/files/home/.${ID}-sound-service
    fi
    echo "pulseaudio --start --exit-idle-time=-1" >> /data/data/com.termux/files/home/.${ID}-sound-service
    echo "pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" >> /data/data/com.termux/files/home/.${ID}-sound-service
	echo "$(echo "bash ~/.${ID}-sound-service" | cat - /data/data/com.termux/files/usr/bin/$ID )" > /data/data/com.termux/files/usr/bin/$ID
	echo "export PULSE_SERVER=127.0.0.1" >> /etc/profile
    source /etc/profile
}

function check_firefox() {
    echo "${R} [${W}-${R}]${Y}Checking if Firefox is installed or not...${W}"
    if ! type -p "firefox" &>/dev/null; then
        sleep 2
        echo "${R} [${W}-${R}]${R}Firefox not installed...${W}"
        firefox_install
    else
        echo "${R} [${W}-${R}]${G}Firefox is already installed.${W}"
    fi
}

function check_chromium() {
    echo "${R} [${W}-${R}]${Y}Checking if Chromium is installed or not...${W}"
    if ! type -p "chromium" &>/dev/null; then
        sleep 2
        echo "${R} [${W}-${R}]${R}Chromium is not installed...${W}"
        install_chromium
    else
        echo "${R} [${W}-${R}]${G}Chromium is already installed.${W}"
    fi
}

function check_install() {
    echo "${R} [${W}-${R}]${Y}Checking if everything is installed or not...${W}"
    sleep 1
    # Desktop check
    echo "${R} [${W}-${R}]${Y}Checking if GNOME installed...${W}"
    if ! type -p "gnome-shell" &>/dev/null; then
	sleep 2
        echo "${R} [${W}-${R}]${R}GNOME Desktop is not installed perfectly...${W}"
		echo "${G}Fixing ..."${W}
        sleep 2
        install_desktop
    else
        echo "${R} [${W}-${R}]${G}GNOME Desktop is Installed Successfully...${W}"
        sleep 2
    fi
    # Browser check
    if [[ "${answer_browser}" == "1" ]]; then
        check_firefox
    elif [[ "${answer_browser}" == "2" ]]; then
        check_chromium
    elif [[ "${answer_browser}" == "3" ]]; then
        check_firefox
        check_chromium
    else
        check_firefox
    fi
    # VLC check
    if [[ "${vlc_answer}" == "y" ]]; then
        echo "${R} [${W}-${R}]${Y}Checking if VLC is installed or not...${W}"
        if ! type -p "vlc" &>/dev/null; then
            sleep 2
            echo "${R} [${W}-${R}]${R}VLC is not installed, installing now...${W}"
            apt install vlc -y
        fi
    fi
}

function note() {
banner
    echo -e "${G} Successfully Installed !"${W}
    sleep 3
	echo
    echo -e "${G}Now Restart Termux First And Login Into $ID "${W}
	echo
    echo -e "${G}Type ${C}$ID${G} to login into $ID "${W}
	echo
    echo "${C}Check the NOTE (👇) section in Github Readme to know all commands"${W}
    echo
    echo "https://github.com/sabamdarif/gnome-in-termux/blob/main/README.md#note"
    echo
}

function change_sources() {
    rm /etc/apt/sources.list 
        touch etc/apt/sources.list
        echo /etc/apt/sources.list "deb http://depo.pardus.org.tr/pardus yirmiuc-deb main contrib non-free non-free-firmware
        deb-src http://depo.pardus.org.tr/pardus yirmiuc-deb main contrib non-free non-free-firmware
        deb http://depo.pardus.org.tr/pardus yirmibir main non-free contrib
        deb-src http://depo.pardus.org.tr/pardus yirmibir main non-free contrib"
}

check_root
get_sys_info
questions
change_sources
update_sys
package
setup_tx11
login
install_desktop
browser_installer
vlc_installer
add_sound
check_install
note
