#!/bin/bash

R="$(printf '\033[1;31m')"
G="$(printf '\033[1;32m')"
Y="$(printf '\033[1;33m')"
W="$(printf '\033[1;37m')"
C="$(printf '\033[1;36m')"

function banner() {
    clear
printf "\033[33m╭━━━╮╱╱╱╱╱╱╱╱╱╱╱╱╭━━╮╱╱╱╭━━━━╮\033[0m\n"
printf "\033[33m┃╭━╮┃╱╱╱╱╱╱╱╱╱╱╱╱╰┫┣╯╱╱╱┃╭╮╭╮┃\033[0m\n"
printf "\033[33m┃┃╱╰╋━╮╭━━┳╮╭┳━━╮╱┃┃╭━╮╱╰╯┃┃┣┻━┳━┳╮╭┳╮╭┳╮╭╮\033[0m\n"
printf "\033[33m┃┃╭━┫╭╮┫╭╮┃╰╯┃┃━┫╱┃┃┃╭╮╮╱╱┃┃┃┃━┫╭┫╰╯┃┃┃┣╋╋╯\033[0m\n"
printf "\033[33m┃╰┻━┃┃┃┃╰╯┃┃┃┃┃━┫╭┫┣┫┃┃┃╱╱┃┃┃┃━┫┃┃┃┃┃╰╯┣╋╋╮\033[0m\n"
printf "\033[33m╰━━━┻╯╰┻━━┻┻┻┻━━╯╰━━┻╯╰╯╱╱╰╯╰━━┻╯╰┻┻┻━━┻╯╰╯\033[0m\n"
echo "${C}${BOLD} Install Gnome Desktop In Termux ${W}"
echo                                                    
}

function check_root(){
	if [ $EUID -ne 0 ]; then
		echo -ne " ${R}Please Login Into Root User Then Run it Again!\n\n"${W}
		exit 1
	fi
}

function questions() {
	banner
	echo 
	echo "${R} [${W}-${R}]${G}Select browser you want to install"${W}
	echo
	echo "${Y}1. firefox"${W}
	echo
	echo "${Y}2. chromium"${W}
	echo 
	echo "${Y}3. firefox & chromium (both)"${W}
	echo
	read -p "${Y}select an option (Default 1): "${W} answer_browser
	banner
	read -p "${R} [${W}-${R}]${Y}Do you want to install VLC (y/n) "${W} vlc_answer
    banner
    read -p "${R} [${W}-${R}]${Y}Do you want to create a normal user account (y/n) "${W} useradd_answer
    useradd_answer="${useradd_answer:-y}"
    banner
#     if [[ "$useradd_answer" == "n" ]]; then
#     banner
#     echo "${R} [${W}-${R}]${G}Skiping User Account Setup"${W}
#     else
#     echo "${R} [${W}-${R}]${G}Create user account"${W}
#     echo
#     while true; do
#     read -p "${R} [${W}-${R}]${G}Input username [Lowercase]: "${W} user_name
#     echo
#     read -p "${R} [${W}-${R}]${G}Input Password: "${W} pass
#     echo
#     read -p "${R} [${W}-${R}]${Y}Do you want to continue with username ${C}$user_name ${Y}and password ${C}$pass${Y} ? (y/n) : " choice
# 	choice="${choice:-y}"
#     case $choice in
#         [yY]* )
#             echo "${R} [${W}-${R}]${G}Continuing with username ${C}$user_name ${G}and password ${C}$pass"
#             sleep 0.3
#             break;;
#         [nN]* )
#             echo "${G}Skipping useradd step"${W}
#             sleep 0.3
#             break;;
#         * )
#             echo "${R}Invalid input. Please enter 'y' or 'n'."${W}
#             ;;
#     esac
# done
#     fi
}

function get_sys_info() {
	if [ -f /etc/os-release ]; then
    . /etc/os-release
	if [[ -e "/data/data/com.termux/files/usr/bin/fedora" ]]; then
        rm -rf /data/data/com.termux/files/usr/bin/fedora
    fi
	fi
}

function update_sys() {
	banner
	echo "${R} [${W}-${R}]${G}Updating fedora's System..."
	dnf update -y
}

function setup_tx11() {
    echo "${G} Fixing gnome black screen issue..."${W}
    find /usr -type f -iname "*login1*" -exec rm -f {} \; && mkdir /run/dbus
    sleep 2
    tx11_answer="tx11_setup_answer"
    if [ "$useradd_answer" = "y" ]; then
    final_user="$user_name"
    else
    final_user="root"
    fi
cat <<EOF >> "/data/data/com.termux/files/usr/bin/fedora"
if [ "\$1" = "-tx11" ]; then
    kill -9 \$(pgrep -f "termux.x11") 2>/dev/null
    pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1
export XDG_RUNTIME_DIR=\${TMPDIR}
termux-x11 :0 >/dev/null &
sleep 3
am start --user 0 -n com.termux.x11/com.termux.x11.MainActivity > /dev/null 2>&1
sleep 1
proot-distro login fedora --shared-tmp -- /bin/bash -c 'export DISPLAY=:0 XDG_RUNTIME_DIR=\${TMPDIR} PULSE_SERVER=127.0.0.1 XDG_CURRENT_DESKTOP="GNOME" && rm -rf /run/dbus/pid && dbus-daemon --system && su - $final_user -c "env DISPLAY=:0 dbus-launch gnome-shell --x11"'
elif [ "\$1" = "-remove" ]; then
    proot-distro remove fedora
	rm \$PREFIX/bin/fedora
elif [ "\$1" = "-r" ]; then
    proot-distro login fedora
else
    proot-distro login --user $final_user fedora
fi
EOF
}

# function login() {
# 	banner
# 	if [ "$useradd_answer" = "y" ]; then
# 	useradd -m -s $(which bash) ${user_name}
#     echo "${user_name}:${pass}" | chpasswd
# 	echo "$user_name ALL=(ALL:ALL) ALL" >> /etc/sudoers
# fi
#     clear   
# }

function vlc_installer() {
	banner
if [ "$vlc_answer" == "y" ]; then
	echo "${R} [${W}-${R}]${G}Installing vlc.."${W}
		dnf install vlc -y
else
    echo "${R} [${W}-${R}]${C}Canceling Vlc Installation...."${W}
    sleep 1.5
fi
}

function install_chromium() {
	banner
	echo "${R} [${W}-${R}]${G} installing chromium..."${W}
    dnf install chromium -y
    sed -i 's/chromium %U/chromium --no-sandbox %U/g' /usr/share/applications/chromium.desktop
}

function firefox_install() {
		clear
		banner
		sleep 1
		clear
        echo "${R} [${W}-${R}]${Y} Installing Firefox..."${W}
		echo
        dnf install firefox -y
}

function browser_installer() {
	banner
	if [[ ${answer_browser} == "1" ]]; then 
		firefox_install
	elif [[ ${answer_browser} == "2" ]]; then
		install_chromium
	elif [[ ${answer_browser} == "3" ]]; then
		firefox_install
		install_chromium
	elif [[ ${answer_browser} == "" ]]; then 
		firefox_install
	else 
		firefox_install
	fi
}
	
function package() {
	banner
    echo -e "${R} [${W}-${R}]${C} Checking required packages..."${W}
    dnf install sudo dbus -y
}

function install_desktop() {
    echo "${R} [${W}-${R}]${G}Installing Gnome Core.."${W}
	sleep 2
    update_sys
    dnf install gnome-shell gnome-terminal gnome-software gnome-tweaks -y
	clear
}

function check_firefox() {
    echo "${R} [${W}-${R}]${Y}Checking if Firefox is installed or not...${W}"
    if ! type -p "firefox" &>/dev/null; then
        sleep 2
        echo "${R} [${W}-${R}]${R}Firefox not installed...${W}"
        firefox_install
    else
        echo "${R} [${W}-${R}]${G}Firefox is already installed.${W}"
    fi
}

function check_chromium() {
    echo "${R} [${W}-${R}]${Y}Checking if Chromium is installed or not...${W}"
    if ! type -p "chromium" &>/dev/null; then
        sleep 2
        echo "${R} [${W}-${R}]${R}Chromium is not installed...${W}"
        install_chromium
    else
        echo "${R} [${W}-${R}]${G}Chromium is already installed.${W}"
    fi
}

function check_install() {
    echo "${R} [${W}-${R}]${Y}Checking if everything is installed or not...${W}"
    sleep 1
    # Desktop check
    echo "${R} [${W}-${R}]${Y}Checking if GNOME installed...${W}"
    if ! type -p "gnome-shell" &>/dev/null; then
	sleep 2
        echo "${R} [${W}-${R}]${R}GNOME Desktop is not installed perfectly...${W}"
		echo "${G}Fixing ..."${W}
        sleep 2
        install_desktop
    else
        echo "${R} [${W}-${R}]${G}GNOME Desktop is Installed Successfully...${W}"
        sleep 2
    fi
    # Browser check
    if [[ "${answer_browser}" == "1" ]]; then
        check_firefox
    elif [[ "${answer_browser}" == "2" ]]; then
        check_chromium
    elif [[ "${answer_browser}" == "3" ]]; then
        check_firefox
        check_chromium
    else
        check_firefox
    fi
    # VLC check
    if [[ "${vlc_answer}" == "y" ]]; then
        echo "${R} [${W}-${R}]${Y}Checking if VLC is installed or not...${W}"
        if ! type -p "vlc" &>/dev/null; then
            sleep 2
            echo "${R} [${W}-${R}]${R}VLC is not installed, installing now...${W}"
            pacman -Sy vlc -y
        fi
    fi
}

function note() {
banner
    echo -e "${G} Successfully Installed !"${W}
    sleep 3
	echo
    echo -e "${G}Now Restart Termux First And Login Into fedora "${W}
	echo
    echo -e "${G}Type ${C}fedora${G} to login into fedora "${W}
	echo
    echo "${C}Check the NOTE (👇) section in Github Readme to know all commands"${W}
    echo
    echo "https://github.com/sabamdarif/gnome-in-termux/blob/main/README.md#note"
    echo
}

check_root
questions
get_sys_info
update_sys
package
login
install_desktop
browser_installer
vlc_installer
check_install
setup_tx11
note
